---
name: PoliceSystem
main: PoliceSystem\main
version: 1.0.0
api:
- 3.0.0
- 4.0.0
- 3.1.4
author: narapon
load: POSTWORLD
commands:
  patrol:
    description: パトロールモード
    usage: /patrol
    aliases:
    - ptl
...
